backend:
  name: git-gateway
  branch: main  # or your Git branch

media_folder: "assets/images" # folder to store uploaded images
public_folder: "/assets/images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Content", name: "body", widget: "markdown" }